//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGRKJYJL
    {
        public string CGRKJYJL_JYLS { get; set; }
        public string CGRKJYJL_JYFL { get; set; }
        public string CGRKJYJL_JYLY { get; set; }
        public string CGRKJYJL_RKLS { get; set; }
        public string CGRKJYJL_RKFL { get; set; }
        public string CGRKJYJL_FPLS { get; set; }
        public string CGRKJYJL_FPFL { get; set; }
        public string CGRKJYJL_WLBH { get; set; }
        public double CGRKJYJL_HXSL { get; set; }
        public double CGRKJYJL_HXDJ { get; set; }
        public string CGRKJYJL_HDBZ { get; set; }
        public double CGRKJYJL_HXJE { get; set; }
    }
}
