//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGRKHX
    {
        public string CGRKHX_FPBH { get; set; }
        public string CGRKHX_FPFLH { get; set; }
        public string CGRKHX_RKBH { get; set; }
        public string CGRKHX_RKFLH { get; set; }
        public string CGRKHX_WLBH { get; set; }
        public string CGRKHX_PCH { get; set; }
        public string CGRKHX_HXRQ { get; set; }
        public double CGRKHX_HXSL { get; set; }
        public double CGRKHX_HXJE { get; set; }
        public double CGRKHX_CGFY { get; set; }
        public string CGRKHX_HXXM { get; set; }
        public double CGRKHX_HXHSJE { get; set; }
    }
}
