//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGWLCGZG
    {
        public string CGWLCGZG_LSBH { get; set; }
        public string CGWLCGZG_WLLB { get; set; }
        public string CGWLCGZG_WLBH { get; set; }
        public string CGWLCGZG_ZYX1 { get; set; }
        public string CGWLCGZG_ZYX2 { get; set; }
        public string CGWLCGZG_ZYX3 { get; set; }
        public string CGWLCGZG_ZYX4 { get; set; }
        public string CGWLCGZG_ZYX5 { get; set; }
        public string CGWLCGZG_JB { get; set; }
        public string CGWLCGZG_ZGBH { get; set; }
        public string CGWLCGZG_BHBZ { get; set; }
    }
}
